config/routes.rb
Rails.application.routes.draw do

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  post 'order_complete' => 'cart#order_complete'

  devise_for :users

  root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category' 

  get 'branding' => 'storefront#items_by_brand'

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, Product
       elsif user.guest?
         can :show, Product
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :product
	belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :line_items
	belongs_to :user

	serialize :order_items, Hash
end

app/models/product.rb
class Product < ApplicationRecord
has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  def admin?
  	role == "admin"
  end      

  def guest?
    role == 'guest'
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :categories, :brands

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
   devise_parameter_sanitizer.permit(:account_update, keys[:role])
  end

  def categories
  	@categories = Category.all
  end

  def brands
  	@brands = Product.pluck(:brand).sort.uniq!
  	if @brands == nil
  		@brands = Product.pluck(:brand).sort
  	end
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	
	before_filter :authenticate_user!, :except => [:add_to_cart, :view_order]

	def add_to_cart
	  line_item = LineItem.create(product_id: params[:product_id], quantity: params[:quantity])

	  line_item.line_item_total = 1 * line_item.product.price
	  line_item.save

	  redirect_to root_path
	end

  def view_order
  	@line_items = LineItem.all
  	@order = Order.create(user_id: current_user.id, subtotal: 0)

	  @line_items.each do |line_item|
	    @order.order_items[line_item.product_id] = line_item.quantity
	    @order.subtotal += line_item.line_item_total
	  end

	  @order.sales_tax = @order.subtotal * 0.07
	  @order.grand_total = @order.subtotal + @order.sales_tax
	  @order.save

	  @line_items.each do |line_item|
	    line_item.quantity
	    line_item.product.save
	  end

  end

	def order_complete
		LineItem.destroy_all

		@order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe customer',
      :currency => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
	end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand, :rating, :category_id, :image)
    end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  before_action :authenticate_user!

  def all_items
  	@products = Product.all
  end

  def items_by_category
  	@products = Product.where(category: params[:cat_id])
  	@category = Category.find(params[:cat_id])
  end

  def items_by_brand
  	@products = Product.where(brand: params[:brand])
  	@brand = params[:brand]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/cart/order_complete.html.erb
<h2>Thank you for your order!</h2>

<h5>
	Order #<%= @order.id %> will be shipping to you, <%= @order.user.email %>, as soon as possible!
</h5>

<h3>Let's review your order:</h3>

<% @order.order_items.each do |k,v| %>
    <ul>
        <li><%= Product.find(k).name %>, <%= v %></li>
    </ul>
<% end %>

<p>
    <strong>Subtotal:</strong> <%= number_to_currency @order.subtotal %>
</p>
<p>
    <strong>Sales Tax:</strong> <%= number_to_currency @order.sales_tax %>
</p>
<p>
    <strong>Order Total:</strong> <%= number_to_currency @order.grand_total %>
</p>

app/views/cart/view_order.html.erb
<h2>My Cart</h2>

<div>
<ul>
  <% @line_items.each do |line_item| %>
    <li><%= line_item.product.name %></li>
    <li><%= number_to_currency line_item.product.price %></li>
    <li>Qty: <%= line_item.quantity %></li>
    <li>Subtotal: <%= line_item.line_item_total %></li>
  <% end %>
  </ul> 
</div>

<div>
	<%= form_tag order_complete_path do %>
		<article>
			<label class="amount">
				<span><%= number_to_currency @order.grand_total %></span>
			</label>
		</article>
		<div>
			<%= hidden_field_tag :order_id, @order.id %>
		</div>

		<script src="http://checkout.stripe.com/checkout.js"
		class="stripe-button"
		data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		data-description="Order #<%= @order.id %>"
		data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab|Raleway" rel="stylesheet">
  </head>

  <body>
  <!-- Navbar Section -->
  <% if user_signed_in? %>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>          
      </button>
        <%= link_to "My Store", root_path, class: "navbar-brand" %>
      </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <% @categories.each do |cat| %>
            <li><%= link_to cat.name, categorical_path(cat_id: cat.id) %></li>
          <% end %>
        </ul>
      </li>
      <!-- Brands -->
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% @brands.each do |brand| %>
            <li><%= link_to brand, branding_path(brand: brand) %></li>
          <% end %>
            <li><%= link_to "All", root_path %></li>
        </ul>
      </li> 
      <!-- End Brands -->
      </ul>
        <ul class="nav navbar-nav navbar-right nav-pills">
          <li><%= link_to current_user.email %></li>
          <li role="presentation" class="active"><%= link_to "My Cart", view_order_path, class: "Add" %><span class="badge"><%= LineItem.count %></span></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </nav>
  <% else %>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>          
      </button>
        <%= link_to "My Store", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Forgot Password", new_user_password_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <% end %>
  	<div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%=f.select(:category_id, @categories.collect {|c| [c.name, c.id]}, { include_blank: "Select Category"})%>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="form-group">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="form-group">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="form-group">
    <strong>Upload Product Image:</strong>
      <%=f.file_field :image%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <td><%= product.category.name %></td>
        <td><%= link_to 'Show', product %></td>
        <% if can? :update, product %>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Product %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/storefront/_display.html.erb
<div class="row">
	<% @products.each do |product| %>
		<div class="col-md-4">
			<div class="well center-it">
				<p><%= image_tag product.image.url(:thumb) %></p>
					<p>
					<a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
						<span class="glyphicon glyphicon-plus"></span> Quick Info
					</a>
				</p>
				<h3><%= product.name %></h3>
				<p><%= number_to_currency product.price %></p>
				<p><%= link_to product.brand, branding_path(brand: product.brand)%></p>
				<p><%= link_to product.category.name, categorical_path(cat_id: product.category_id) %></p>
				<%= form_tag add_to_cart_path do %>
				  <%= hidden_field_tag :product_id, product.id %>
				<button type="submit">
   				<span class="glyphicon glyphicon-shopping-cart">
				  <% end %>
				  </span>
				</button>
			</div>
		</div>
		<!-- Modal -->
			<div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="myModalLabel"><%= product.name %></h4>
			      </div>
			      <div class="modal-body">
			        <p><%= product.price %></p>
			        <p><%= product.description %></p>
			      </div>
			    </div>
			  </div>
			</div>
	<% end %>
</div>

app/views/storefront/all_items.html.erb
<h1>Welcome to My Store</h1>
<h4>Gimmie yo money!</h4>

<%= render 'display' %>

app/views/storefront/items_by_brand.html.erb
<h1>All of our <%= @brand %> Products</h1>

<%= render 'display' %>

app/views/storefront/items_by_category.html.erb
<h1>All of our <%= @category.name %></h1>

<%= render 'display' %>